### ISSUE TITLE
NPM Module doesn't match source code

### ISSUE THREAD

**Issue by aav7fl** [alex-okrushko/backoff-rxjs#11]
Hey, I'm having an issue with the latest NPM module `6.1.0`. I think it's still using the old code for `maxAttempts` even though the source code is showing `maxRetries`. 

Could you bump up to a new version with the latest source code? I'm getting quite a few errors of missing parameters because of this difference.

**Comment by alex-okrushko** [comment]
Ouch. Re-published to npm.

Thanks for letting me know!

**Comment by aav7fl** [comment]
Hmm... I'm not quite sure what's up. After reinstalling the `backoff-rxjs` npm module with the latest version (`6.1.1`), I'm still showing that the file: `node_modules\backoff-rxjs\dist\operators\retryBackoff.d.ts` still contains `maxAttempts` instead of `maxRetries`.

Am I using this incorrectly?

**Comment by alex-okrushko** [comment]
Ok, building it before publishing should help :P

**Comment by aav7fl** [comment]
Awesome! We're good to go. `6.1.2` works great. Thanks! ❤️
