### ISSUE TITLE
When importing retryBackoff in Angular Project, bundle size is increasing astronomically

### ISSUE THREAD

**Issue by SplitterAlex** [alex-okrushko/backoff-rxjs#12]
Hello!

I am using backoff-rxjs in one of my angular projects and after analyzing my main bundle size I discovered my rxjs related imports are 126KB and this cannot be true. After some investigation I discovered the rxjs bundle is increasing astronomically when using the backoff-rxjs operator in my project.

I tested this behaviour on a freshly generated Angular CLI Project via `ng new` (CLI Version: 7.3.0). When building (`ng build --prod`) this simple project the rxjs related part in the main bundle is **~17KB**. After importing `retryBackoff` and using it in the `AppComponent` like shown below, the rxjs related part in the main bundle is now at **~123.8KB**. Mainly because wepback is packing the whole RXJS library inside the main bundle.

```typescript
import { Component, OnInit } from '@angular/core';
import { of } from 'rxjs';
import { retryBackoff } from 'backoff-rxjs';

@Component({
  selector: 'app-root',
  template: `
    <div>AppComponent</div>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  ngOnInit() {
    of('')
      .pipe(
        retryBackoff({
          initialInterval: 200,
          maxRetries: 3
        })
      )
      .subscribe(d => console.log);
  }
}
```
For source map visualation I used [source-map-explorer](https://github.com/danvk/source-map-explorer).

### Before usage of `retryBackoff`

![before-import](https://user-images.githubusercontent.com/9348109/52037967-a3b83e80-256b-11e9-931f-cc95962bac1c.png)

### After usage of `retryBackoff`

![after-import](https://user-images.githubusercontent.com/9348109/52037979-b0d52d80-256b-11e9-9473-2f0baf8a6f7a.png)

**Comment by alex-okrushko** [comment]
<img width="1414" alt="screen shot 2019-01-31 at 11 53 36 pm" src="https://user-images.githubusercontent.com/2830407/52103499-f4ec2080-25b3-11e9-8ff0-ff52ad8c7007.png">

Using `es2015` instead of `commonjs` fixes the problem. Apparently commonJS doesn't have the concept of tree-shaking.

**Comment by alex-okrushko** [comment]
Pushed 6.2.2 to npm and verified that it works as expected:

<img width="1399" alt="screen shot 2019-02-01 at 12 03 52 am" src="https://user-images.githubusercontent.com/2830407/52103695-f23dfb00-25b4-11e9-8c8e-708f160fbd26.png">

Thanks a lot for the issue report @SplitterAlex ! 👍
