### ISSUE TITLE
Catch error and retry?

### ISSUE THREAD

**Issue by ap1969** [alex-okrushko/backoff-rxjs#16]
Hi Alex,

I've not been able to find a way to both catch the http error object, and also retry with the interval. It seems that whichever one I put into the .pipe() first, that first one is executed, but not the second.

Have you got an example of doing this?

The use case is that during the app initialisation, it needs to register with the server. I want to display an error message to say a user-friendly error message whilst still retryng in the background.

Thanks for your work on this by the way, I'm surprised this functionality isn't built into RxJS already.

Regards,
Andy

**Comment by LosD** [comment]
@ap1969 Part of the idea behind catch is that it won't continue down the pipe. Couldn't you rethrow the caught error, like in this example?
https://blog.angular-university.io/rxjs-error-handling/#thecatchandrethrowstrategy

**Comment by alex-okrushko** [comment]
@ap1969 Thanks for the issue.

That looks like a side-effect for me, which could be intercepted with `tap`, maybe something like this:

```ts
this.service.call(arguments).pipe(
  tap({
    // 👇 performing the side-effect on error only
    error: error => {
      this.errorMessages$.next(error);
    }
  }),
  retryBackoff(1000),
  tap(() => {
    // clear the messages on success
     this.errorMessages$.next(undefined);
  })
)
```

I'm sure there could be a better solution, but that's the first that comes to mind.
